/* FILTRANDO */
SELECT NOME, SEXO FROM CLIENTE WHERE SEXO = 'M'; 

SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO LIKE '%RJ || RJ%';  /*LIKE  CARACTER CORINGA % --> QUALQUER COISA*/



/*TECNOLOGIA --> AJAX FAZ BUSCA EM TEMPO REAL NO BANCO DE DADOS */
