/* OPERADORES LÓGICOS 
OR	-->	PARA QUE A SAIDA DA QUERY SEJA VERDADEIRA, BASTA QUE APENAS UMA CONDICAO SEJA VERDADEIA
AND	-->	PARA QUE A SAIDA SEJA VERDADEIRA TODAS AS CONDIÇÕES PRECISAM SER VERDADEIRAS.
*/
SELECT nome, sexo, endereco 
FROM cliente 
WHERE sexo = 'M' OR endereco LIKE '%RJ';


