/* PRIMEIRA FORMA NORMAL */

/*

1 - TODO CAMPO VETORIZADO SE TORNARA OUTRA TABELA

    EXEMPLO = TELEFONE PODE TER MAIS DE UM 
                = EMAIL
            = ENDERECO
            = CARRO

2 - TODO CAMPO MULTIVALORADO SE TORNARA OUTRA TABELA
    QUANDO CAMPO FOR DIVISIVEL
    Exemplo: cada um dos itens se tornara uma tabela.
        ENDERECO => RUA, CIDADE, ESTADO

3 - TODA TABELA NECESSITA DE PELO MENSO UM CAMPO QUE IDENTIFIQUE 
    TODO O REGISTRO COMO SENDO UNICO.
    ISSO E QUE CHAMAMOS DE CHAVE PRIMARIA 

    Mais utilizado é o (ID)
  
*/